In [1]:
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error 
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
warnings.filterwarnings('ignore', category=DeprecationWarning)
from xgboost import XGBRegressor

Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [2]:
def get_data():
    data = pd.read_csv("train.csv") 
    Y=data.iloc[:, 2]
    X=data.iloc[:, 4:21]
    test2019X=data.iloc[:, 21:38]
    z=data.iloc[:, 38]
    z.to_numpy()
    X["LC_Type1_mode"]=z
    X["X"]=data.iloc[:, 0].to_numpy()
    X["Y"]=data.iloc[:, 1].to_numpy()
    X["elevation"]=data.iloc[:, 3].to_numpy()
    test2019Y = pd.read_csv("SampleSubmission.csv") 
    test2019Y=test2019Y.iloc[:,1]
    test2019X["LC_Type1_mode"]=data.iloc[:, 38].to_numpy()
    test2019X["X"]=data.iloc[:, 0].to_numpy()
    test2019X["Y"]=data.iloc[:, 1].to_numpy()
    test2019X["elevation"]=data.iloc[:, 3].to_numpy()
    X=X.to_numpy()
    Y=Y.to_numpy()
    test2019X=test2019X.to_numpy()
    test2019Y=test2019Y.to_numpy()
    X_train, X_cv, Y_train, Y_cv = train_test_split(X, Y, test_size=0.3, random_state=42)
    
    return X_train,Y_train,X_cv,Y_cv






In [10]:
import numpy as np
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(4, 3) # b.shape = (3, 2)
c = a*b
print(a)
print(b)
print(c)

[[-0.76627861  0.96673761  0.54936831]
 [-0.89835737  0.80709499  0.96926733]
 [-0.07224619  0.4926033  -1.04886296]
 [ 1.21827385  0.07873574 -1.6256535 ]]
[[ 1.65906474  0.8855949  -1.31269051]
 [-0.01179229 -0.38366536  0.14615672]
 [-0.42208642  1.18690739  0.23070468]
 [ 2.28100563 -0.62101221  0.06724227]]
[[-1.27130582  0.85613789 -0.72115057]
 [ 0.01059369 -0.30965439  0.14166494]
 [ 0.03049414  0.58467449 -0.24197759]
 [ 2.77888951 -0.04889586 -0.10931264]]


In [28]:
import math
# GRADED FUNCTION: L1

def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = np.dot(yhat-y,yhat-y).sum()
    ### END CODE HERE ###
    
    return loss
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 0.43


# **Expected Output**:

<table style="width:60%">

     <tr> 
       <td> **softmax(x)** </td> 
       <td> [[  9.80897665e-01   8.94462891e-04   1.79657674e-02   1.21052389e-04
    1.21052389e-04]
 [  8.78679856e-01   1.18916387e-01   8.01252314e-04   8.01252314e-04
    8.01252314e-04]]</td> 
     </tr>
</table>